### PR TITLE
Shorten config.txt url

### PR DESCRIPTION
**Pull request by bennuttall**
Because why not? :)

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Backwards compatibility?

**Comment by XECDesign** [comment]
Might be a bit too late. That was the link I was given to use and raspberrypi-sys-mods updates it on existing installs:
https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/debian/raspberrypi-sys-mods.postinst#L61

Now it would need to be something like:
If updating from this version or older, change this URL to this other URL.
If updating from this other version, change this other URL to yet another URL.

It would be nice to avoid touching config files whenever possible.
Do you feel like it's  enough of an issue?

**Comment by bennuttall** [comment]
Not essential, just a shame the short url was created unnecessarily long.

**Comment by XECDesign** [comment]
I think I'll merge this and sort out sys-mods next time it's modified. Thanks.

**Pull request merged**
