### PR TITLE
Export base directory before loading config file

### PR DESCRIPTION
**Pull request by LCvanDinteren**
By exporting the base directory before loading config, it is possible to use the base dir within the config file.

### CODE REVIEW

**Comment by XECDesign** [comment]
I suspect shellcheck wouldn't be happy with that and want the assignment and export on separate lines.

**Comment by LCvanDinteren** [comment]
> I suspect shellcheck wouldn't be happy with that and want the assignment and export on separate lines.

This same structure is used for many exports below, which is why I chose to keep in line with those lines.
Do you suggest something like this? :
```
if [ -z "${BASE_DIR}" ]; then
  BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi
export BASE_DIR
```

**Comment by XECDesign** [comment]
I didn't know about shellcheck when I wrote the first version, so I wouldn't be surprised. Just trying to stick to better practices now.

In most case, an export and assignment on the same line is fine because there's no command substitution. In this case, because the assignment can fail, you'd want to catch that (which doesn't happen if you export on the same line).

I'm not sure the `[ -z "${BASE_DIR}" ]` would make sense. What would be the use case for setting a BASE_DIR that's outside of build.sh? Has that use case been tested to work with that change or would it also be broken in other ways?

I think if you move the existing BASE_DIR= and export BASE_DIR lines up so that's they're after the root user check, it should be fine.

**Comment by LCvanDinteren** [comment]
Alright, always a fan of better practices:)

I can't think of any use for defining BASE_DIR outside of build.sh, but figured that as I'm changing it anyway, might as well align it with the rest of the code.

Updated as per your suggestion.

**Comment by XECDesign** [comment]
Just one last thing. There's a stray `export BASE_DIR` here https://github.com/RPi-Distro/pi-gen/blob/97076ab9f849c088e256e0bf6ba9f074d1ec0a7b/build.sh#L183

**Comment by LCvanDinteren** [comment]
Nice catch, my bad!

**Comment by XECDesign** [comment]
Many thanks

**Comment by LCvanDinteren** [comment]
Many thanks to you as well!

**Pull request merged**
