### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by voipminic**
apt-transport-https is required too

### CODE REVIEW

**Comment by XECDesign** [comment]
Why would that be required?

**Comment by r4and0m0** [comment]
I had to install that package too on latest xubuntu lts some time ago, the script just complained about the missing package and aborted the job.
BTW
At this moment the repo still have the old version of rpigen ? it generate just 2 img, lite and full(whitout mathematica)

**Comment by XECDesign** [comment]
sorry @r4and0m0, didn't see your message before.

I think the repo should be up to date now and have all the variants.

I can't find anything in pi-gen that requires  apt-trasport-https. I'm open to being proven wrong, but with a full explanation of what's going on, because I'm not seeing it.

**Comment by r4and0m0** [comment]
For me the script complained about the missing package apt-transport-https then stopped (happen like all other dependecys(is missing)) so when i installed the https apt transport package i was able to build any image.

**Pull request closed without merging**
