### PR TITLE
Selection for the last stage to build

### PR DESCRIPTION
**Pull request by jacen92**
Should solve Feature Request: Modular Builds #93

Allows dev to set the last build step without adding SKIP file and removing stuff in the project.

### CODE REVIEW

**Comment by XECDesign** [comment]
pi-gen should be fairly agnostic about what it's actually building. It shouldn't assume how many stages there are or which of them are exported. The validation check and default value don't quite make sense in that context.

**Comment by jacen92** [comment]
but each step depends of the previous right? in fact they have an order an devs know which is the last if he add more stage. It is not dynamically set or changed

**Comment by XECDesign** [comment]
Yes, but a person customising a distro or creating their own shouldn't need to touch build.sh and the documentation shouldn't assume we're building the official rpf raspbian image.

**Comment by jacen92** [comment]
I will make a new one later

**Pull request closed without merging**
