### PR TITLE
[fixing] docker parts

### PR DESCRIPTION
**Pull request by jacen92**
Use $DOCKER in build-docker instead of just docker command when necessary and remove container if build succeed

### CODE REVIEW

**Comment by XECDesign** [comment]
Will leave this open for a while for people who use docker to comment, in case there is something wrong.

**Comment by jacen92** [comment]
I tried an hour ago and it works but I understand.

wait and see

**Comment by cfstras** [comment]
works for me.

**Comment by XECDesign** [comment]
Thank you both.

**Pull request merged**
