### PR TITLE
Automagically use i386/debian:buster

### PR DESCRIPTION
**Pull request by aniongithub**
when running on 64-bit host to prevent error #271

### CODE REVIEW

**Comment by rnestler** [comment]
Does this really work around the issue? Isn't just the host version of `qemu-arm-static` used anyways?

**Comment by rnestler** [comment]
> Does this really work around the issue? Isn't just the host version of qemu-arm-static used anyways?

I tested it and it seems to work indeed.

**Comment by cvabc** [comment]
It seems with this fix, `blkid` will not show USB disk?

**Comment by XECDesign** [comment]
Sorry about the delay.

**Pull request merged**
