### PR TITLE
Support regional config settings

### PR DESCRIPTION
**Pull request by jbussdieker**
Addresses some of the concerns in issue #212. For me it's mostly about fixing the issue where `|` on my keyboard incorrectly maps to `~`.

### CODE REVIEW

**Comment by jbussdieker** [comment]
Addresses some of the concerns in issue #212.

**Comment by jbussdieker** [comment]
Yes it's been tested.

**Comment by jbussdieker** [comment]
From what I can tell `capsh` or `EOS` is handling the shell expansion.

**Comment by XECDesign** [comment]
Thank you. I know people have been asking for this for ages.

**Pull request merged**
