### PR TITLE
Expand trap cleanup function

### PR DESCRIPTION
**Pull request by tdewey-rpi**
Add a function to unmount the bindmounts in the chroot, and unmount the image and stage in progress, in the event of a trap.

### CODE REVIEW

**Comment by tdewey-rpi** [comment]
Wait, what? I can't see why this has brought in those other two commits....

**Comment by tdewey-rpi** [comment]
Paging @XECDesign for a view.

**Comment by tdewey-rpi** [comment]
Confirmed I see this more gracefully handling fatal errors

**Comment by XECDesign** [comment]
Is `off_chroot` needed? 

I believe the `unmount "${WORK_DIR}/${STAGE}"` line should already do everything the `off_chroot` function would've done.

The `on` in `on_chroot` maybe should've been `in`. The idea is that you pipe commands into it and it runs in the chroot environment.

Or have I missed something?

**Comment by tdewey-rpi** [comment]
> Is `off_chroot` needed?
> 
> I believe the `unmount "${WORK_DIR}/${STAGE}"` line should already do everything the `off_chroot` function would've done.
> 
> The `on` in `on_chroot` maybe should've been `in`. The idea is that you pipe commands into it and it runs in the chroot environment.
> 
> Or have I missed something?

I found without this, I was still getting sub-mounts mounted on abort - which then caused trouble when I tried delete the workdir and re-try my build.

RE: naming:

Completely my fault for misreading. Happy to rename.

**Comment by XECDesign** [comment]
This version, which also includes #771, works for me without `off_chroot` with failures introduced in various sub-stages and also in export-image while the img file is attached.

Rebased off the `master` branch, since that's what gets merge into `arm64`

The current git history is just for testing and clarity, so I've converted it to a draft for now

**Comment by XECDesign** [comment]
Also, thanks! This has been a long overdue addition.

**Comment by tdewey-rpi** [comment]
@XECDesign Yours to merge, I lack the powers for now.

**Pull request merged**
